<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
  <PropertyGroup>

    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath>
	<Version>1.0.0b</Version>
	<ApplicationDisplayVersion>$(Version)</ApplicationDisplayVersion>
	<ApplicationVersion>1</ApplicationVersion>

  </PropertyGroup>
</Project>
