<Project>
  <!-- See https://aka.ms/dotnet/msbuild/customize for more details on customizing your build -->
  <PropertyGroup>

    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath>
	<Version>1.0.1</Version>
	<ApplicationDisplayVersion>$(Version)</ApplicationDisplayVersion>
	<ApplicationVersion>2</ApplicationVersion>

  </PropertyGroup>
</Project>
