<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
  	<DebugType>none</DebugType>
  	<DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Labs.Lottie" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="HtmlAgilityPack" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Svg.Controls.Skia.Avalonia" />
    <PackageReference Include="Xamarin.Essentials" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Desktop\MainViewDesktop.axaml.cs">
      <DependentUpon>MainViewDesktop.axaml</DependentUpon>
    </Compile>
	<Compile Update="Views\Mobile\MainViewMobile.axaml.cs">
		<DependentUpon>MainViewMobile.axaml</DependentUpon>
	</Compile>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="StudentAccountTSTU.Crypto">
      <HintPath>..\libs\StudentAccountTSTU.Crypto.dll</HintPath>
    </Reference>
    <Reference Include="WebAccount">
      <HintPath>..\libs\WebAccount.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
