<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ApplicationId>com.CompanyName.StudentAccountTSTU</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <AssemblyName>LKS_TGTU</AssemblyName>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Icon.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Android" />
    <PackageReference Include="Xamarin.AndroidX.Core.SplashScreen" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StudentAccountTSTU\StudentAccountTSTU.csproj" />
  </ItemGroup>
	
  <Target Name="RenameApkToAssemblyName" AfterTargets="Build;SignAndroidPackage;Publish">
  
  	<ItemGroup>
  		<_SignedPkgs Include="$(OutputPath)**\$(ApplicationId)-Signed.apk;$(OutputPath)**\$(ApplicationId)-Signed.aab" />
  		<_SignedPkgs Include="$(PublishDir)**\$(ApplicationId)-Signed.apk;$(PublishDir)**\$(ApplicationId)-Signed.aab" Condition="'$(PublishDir)' != ''" />
  	</ItemGroup>
  	<Move SourceFiles="@(_SignedPkgs)"
          DestinationFiles="@(_SignedPkgs->'%(RootDir)%(Directory)$(AssemblyName)-Signed%(Extension)')"
          Condition="'@(_SignedPkgs)' != ''" />
  
  	<ItemGroup>
  		<_UnsignedPkgs Include="$(OutputPath)**\$(ApplicationId).apk;$(OutputPath)**\$(ApplicationId).aab" />
  		<_UnsignedPkgs Include="$(PublishDir)**\$(ApplicationId).apk;$(PublishDir)**\$(ApplicationId).aab" Condition="'$(PublishDir)' != ''" />
  	</ItemGroup>
  	<Move SourceFiles="@(_UnsignedPkgs)"
          DestinationFiles="@(_UnsignedPkgs->'%(RootDir)%(Directory)$(AssemblyName)%(Extension)')"
          Condition="'@(_UnsignedPkgs)' != ''" />
  
  </Target>
</Project>
